
CREATE TABLE IF NOT EXISTS afp_case_verification
(
   starttime VARCHAR
 , endtime VARCHAR
 , today VARCHAR
 , deviceid VARCHAR
 , gps1 VARCHAR
 , gps1_latitude VARCHAR
 , gps1_longitude VARCHAR
 , gps1_altitude VARCHAR
 , gps1_precision VARCHAR
 , date_case_verified VARCHAR
 , date_onset VARCHAR
 , zones VARCHAR
 , states VARCHAR
 , epid VARCHAR
 , epid_generate VARCHAR
 , "extract" VARCHAR
 , epid_num VARCHAR
 , note1 VARCHAR
 , lgas VARCHAR
 , wards VARCHAR
 , ward_code VARCHAR
 , verify_person VARCHAR
 , verify_person_other VARCHAR
 , verify_title VARCHAR
 , verify_title_other VARCHAR
 , town_city VARCHAR
 , address VARCHAR
 , settlement_vill VARCHAR
 , afp_name VARCHAR
 , father_name VARCHAR
 , mother_name VARCHAR
 , informant VARCHAR
 , relate_inform VARCHAR
 , dob VARCHAR
 , age_years VARCHAR
 , age_months VARCHAR
 , sex VARCHAR
 , setting VARCHAR
 , setting_other VARCHAR
 , religion VARCHAR
 , religion_other VARCHAR
 , other_child VARCHAR
 , lang_hh VARCHAR
 , lang_hh_other VARCHAR
 , lang_area VARCHAR
 , lang_area_other VARCHAR
 , normadic VARCHAR
 , normad_type VARCHAR
 , normad_type_other VARCHAR
 , child_travel30 VARCHAR
 , num_lga_child_visited VARCHAR
 , travel1 VARCHAR
 , travel1date VARCHAR
 , travel2 VARCHAR
 , travel2date VARCHAR
 , travel3 VARCHAR
 , travel3date VARCHAR
 , travel4 VARCHAR
 , travel4date VARCHAR
 , fever_onset VARCHAR
 , asymetric VARCHAR
 , progmaxim VARCHAR
 , ascend_paralysis VARCHAR
 , history_injection VARCHAR
 , inject_date VARCHAR
 , admit_hosp VARCHAR
 , admit_date VARCHAR
 , med_record VARCHAR
 , facility_name VARCHAR
 , seek_help VARCHAR
 , place1 VARCHAR
 , place1person VARCHAR
 , place1date VARCHAR
 , place2 VARCHAR
 , place2person VARCHAR
 , place2date VARCHAR
 , place3 VARCHAR
 , place3person VARCHAR
 , place3date VARCHAR
 , place4 VARCHAR
 , place4person VARCHAR
 , place4date VARCHAR
 , riopv VARCHAR
 , reason_ri_zero VARCHAR
 , hist_opv VARCHAR
 , siaopv VARCHAR
 , reason_sia_zero VARCHAR
 , reason_sia_zero_other VARCHAR
 , ipv_ri_sia VARCHAR
 , ipvdate VARCHAR
 , opv_birth VARCHAR
 , opv1date VARCHAR
 , opv2date VARCHAR
 , opv3date VARCHAR
 , opv4date VARCHAR
 , last_opv_date VARCHAR
 , gps2 VARCHAR
 , gps2_latitude VARCHAR
 , gps2_longitude VARCHAR
 , gps2_altitude VARCHAR
 , gps2_precision VARCHAR
 , stool1date VARCHAR
 , stool2date VARCHAR
 , specimen_reach_lab VARCHAR
 , "DateStoolSentolab" VARCHAR
 , "inv1stDate" VARCHAR
 , rul_tone VARCHAR
 , rll_tone VARCHAR
 , lul_tone VARCHAR
 , lll_tone VARCHAR
 , rul_reflex VARCHAR
 , rll_reflex VARCHAR
 , lul_reflex VARCHAR
 , lll_reflex VARCHAR
 , intcranal VARCHAR
 , "incranRight" VARCHAR
 , "incranLeft" VARCHAR
 , int_muscle VARCHAR
 , int_pain VARCHAR
 , "inv1stName" VARCHAR
 , "inv1stTitle" VARCHAR
 , "inv1stTitle_other" VARCHAR
 , verify_afp VARCHAR
 , phys_diagnosis VARCHAR
 , phys_diagnosis_other VARCHAR
 , "diagDescrip" VARCHAR
 , pyhsician VARCHAR
 , "phyImpression" VARCHAR
 , "phyImpression_other" VARCHAR
 , "hotCase" VARCHAR
 , "hotDsno" VARCHAR
 , "otherNotes" VARCHAR
 , "meta_instanceID" VARCHAR
 , id VARCHAR
 , uuid VARCHAR
 , index VARCHAR
 , parent_table_name VARCHAR
 , parent_index VARCHAR
 , tags VARCHAR
 , notes VARCHAR
 , version VARCHAR
 , duration VARCHAR
 , submitted_by VARCHAR
 , child_seen VARCHAR
 , history_flacid VARCHAR
 , zone_onset VARCHAR
 , zones_staff VARCHAR
 , "summary1_Inadequate" VARCHAR
 , "summary1_AgeInDays" VARCHAR
 , verify_impression VARCHAR
 , reflexes VARCHAR
 , "site_paralysis_None" VARCHAR
 , "site_paralysis_LUL" VARCHAR
 , "Received_RI" VARCHAR
 , tone VARCHAR
 , "site_paralysis_RLL" VARCHAR
 , childabsent_other VARCHAR
 , lga_onset VARCHAR
 , power VARCHAR
 , reason_ri_zero_other VARCHAR
 , injection_serve_other VARCHAR
 , region_of_case VARCHAR
 , "normad_type_Farmers" VARCHAR
 , "normad_type_Fishermen" VARCHAR
 , provision_diag VARCHAR
 , relate_inform_other VARCHAR
 , lga_notification VARCHAR
 , totalpoliodoses VARCHAR
 , zone_notification VARCHAR
 , medical_doctor VARCHAR
 , int_district VARCHAR
 , yesdob VARCHAR
 , site_paralysis VARCHAR
 , injection_serve VARCHAR
 , "summary1_HotCase" VARCHAR
 , "summary1_Approp_Imm" VARCHAR
 , childabsent VARCHAR
 , state_onset VARCHAR
 , verify_impression_other VARCHAR
 , "DateNotified" VARCHAR
 , states_staff VARCHAR
 , "site_paralysis_LLL" VARCHAR
 , "site_paralysis_RUL" VARCHAR
 , caregiver_know_2ndstool VARCHAR
 , justification VARCHAR
 , num_place_visited VARCHAR
 , normad_type_other1 VARCHAR
 , "SourceInfo_RI" VARCHAR
 , "normad_type_Herdsmen" VARCHAR
 , ward_onset VARCHAR
 , "interviewed_by_DSNO" VARCHAR
 , stool24 VARCHAR
 , ward_notification VARCHAR
 , int_bor VARCHAR
 , int_border VARCHAR
 , state_notification VARCHAR
 , CONSTRAINT afp_case_verification_epid_num_ux UNIQUE(epid_num)
);