- pipeline.id: msts_odk_data
  path.config: "/usr/share/logstash/pipeline/logstash_msts_odk_data.conf"
  pipeline.workers: 1
- pipeline.id: outside_monitoring
  path.config: "/usr/share/logstash/pipeline/logstash_outside_monitoring.conf"
  pipeline.workers: 1
- pipeline.id: redo_data
  path.config: "/usr/share/logstash/pipeline/logstash_redo_data.conf"
  pipeline.workers: 1
- pipeline.id: tallysheet
  path.config: "/usr/share/logstash/pipeline/logstash_tallysheet.conf"
  pipeline.workers: 1
- pipeline.id: vaccine
  path.config: "/usr/share/logstash/pipeline/logstash_vaccine.conf"
  pipeline.workers: 1
- pipeline.id: afp_case_based
  path.config: "/usr/share/logstash/pipeline/logstash_afp_case_based_data.conf"
  pipeline.workers: 1
- pipeline.id: lqas_opv
  path.config: "/usr/share/logstash/pipeline/logstash_lqas_opv_data.conf"
  pipeline.workers: 1
- pipeline.id: afp_case_verification
  path.config: "/usr/share/logstash/pipeline/logstash_afp_case_verification_data.conf"
  pipeline.workers: 1
- pipeline.id: intra_campaign_dashboard
  path.config: "/usr/share/logstash/pipeline/logstash_intra_campaign_data.conf"
  pipeline.workers: 1
- pipeline.id: pre_campaign_dashboard
  path.config: "/usr/share/logstash/pipeline/logstash_pre_campaign_data.conf"
  pipeline.workers: 1
- pipeline.id: vcm_h2h
  path.config: "/usr/share/logstash/pipeline/logstash_vcm_h2h_data.conf"
  pipeline.workers: 1
- pipeline.id: vcm_settlement_ipd_summary
  path.config: "/usr/share/logstash/pipeline/logstash_vcm_settlement_ipd_summary_data.conf"
  pipeline.workers: 1
- pipeline.id: vcm_settlement_summary_data
  path.config: "/usr/share/logstash/pipeline/logstash_vcm_settlement_summary_data.conf"
  pipeline.workers: 1
- pipeline.id: ihh_endprocess_monitoring_data
  path.config: "/usr/share/logstash/pipeline/logstash_inside_monitoring_data.conf"
  pipeline.workers: 1